### ISSUE TITLE
Getting Started documentation

### ISSUE THREAD

**Issue by mdjebaile** [mayteio/ra-aws-amplify#15]
First of all, thank you for your work. 
We are a small startup that is really depending on the future of this Data Provider, and we cannot make it work even from a fresh clean project.
Can you please document in the README how to get a small example running from scratch?
Thank you again!

**Comment by mayteio** [comment]
No problem, glad it’s handy. I can certainly add some “getting started” documentation. What is missing from the “usage” section? Did you check out the example folder in the meantime? Can you provide code examples of what isn’t working?

**Comment by mdjebaile** [comment]
Super handy. I reckon there are hundreds/thousand of devs watching this space while Amplify gets popular.

So I tried adding it to my Amplify project (from [Getting Started tutorial](https://docs.amplify.aws/start/q/integration/react) and getting "Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons" (https://reactjs.org/docs/hooks-rules.html).

I also tried running from your example and getting babel issues. At the moment I'm not with my laptop but I still wanted to reply quickly. I will get the code examples ASAP.
Thanks again! And if you have time, can you try doing [the 5 minutes tutorial from Amplify](https://docs.amplify.aws/start/q/integration/react) and try adding ra-aws-amplify on top. I reckon that's the flow most of devs are doing right now.
Cheers!

**Comment by mayteio** [comment]
Thank you for the report. I will look into it first thing in the morning (dinner time here) and will get back to you ASAP. Please shoot through a code sandbox if you can in the meantime.

**Comment by mdjebaile** [comment]
It is working perfectly, it was a problem I had here between the screen and the chair haha. Please, feel free to close this one ;)
Thanks mate

**Comment by mayteio** [comment]
Ah, good old PEBKAC. no problem, let me know if I can help with anything else. Cheers
